est_hardware_sub:
  ros__parameters:
    log_name: "b1_mhe_with_gt"

    prior:
      p_init_std: [0.01, 0.01, 0.01]
      v_init_std: [0.01, 0.01, 0.01]
      foot_init_std: [0.01, 0.01, 0.01]
      accel_bias_init_std: [0.001, 0.001, 0.001]
      GM_init_std: [0.01, 0.01, 0.01]
      GRF_init_std: [0.01, 0.01, 0.01]
      GM_Torso_init_std: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
      Force_Torso_init_std: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01]

    process:
      p_process_std: [0.001, 0.001, 0.001]
      accel_input_std: [0.09, 0.09, 0.09] 
      gyro_input_std: [0.02, 0.02, 0.02] 
      accel_bias_process_std: [0.01, 0.01, 0.01]
      GM_process_std: [0.01, 0.01, 0.01]
      GRF_process_std: [100., 100., 100.]
      GM_Torso_process_std: [5.7, 5.7, 8.7, 1.3, 1.3, 1.3]
      Force_Torso_process_std: [100., 100., 100., 100., 100., 100.]

    leg_odom:
      quaternion_ib: [1.0, 0.0, 0.0, 0.0] # [w, x, y, z]
      p_ib: [0.0, 0.0, 0.0]
      num_leg: 4
      num_joints: 3
      using_lo_p: 0
      using_lo_v: 1
      joint_position_std: [0.01, 0.01, 0.01]
      joint_velocity_std: [0.025, 0.025, 0.025]
      foot_slide_std: [0.0001, 0.0001, 0.0001]
      foot_swing_std: [100.0, 100.0, 100.0]
      contact_effort_theshold: 150.0
      GM_meas_gyro_std: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
      GM_meas_foot_std: [0.01, 0.01, 0.01]

    visual_odom:
      vo_p_std:  [0.00005, 0.00005, 0.00005]
    
    estimation:
      rate: 200
      interval: 5.0
      N: 4
      est_type: 0
      est_GRF: 1
      est_Torso: 0
      using_impact_map: 0

    osqp:
      rho: 0.1
      alpha: 1.6
      delta: 0.00001
      sigma: 0.00001
      verbose: true
      adaptRho: true
      polish: false
      maxQPIter: 4000
      primTol: 1e-8
      dualTol: 1e-8
      realtiveTol: 1e-8
      absTol: 1e-8
      timeLimit: 0.003

vo_sub:
  ros__parameters:  
    # # vo_calibration_params
    # # T_ic:  (cam0 to imu0): 
    # # [[-0.00505796 -0.00712053  0.99996186  0.27624613]
    # # [-0.99978629 -0.02000842 -0.00519955  0.11156406]
    # # [ 0.02004468 -0.99977446 -0.0070178   0.12934819]
    # # [ 0.          0.          0.          1.        ]]
    R_ic: 
      [-0.01197093, -0.01305375, 0.99984314,
      -0.99972561, -0.01997792, -0.01223036,
      0.02013444, -0.9997152,  -0.01281101]
    p_ic: [0.31774237, -0.04169241, 0.08706372]

    image_topic_left: "/camera/infra1/image_rect_raw"
    image_topic_right: "/camera/infra2/image_rect_raw"

orien_sub:
  ros__parameters: 
    quaternion_init: [1.0, 0.0, 0.0, 0.0] # [w, x, y, z]
    init_std: [0.0001, 0.0001, 0.0001, 0.0001]
    process_std: [0.1, 0.1, 0.1]
    gravity_meas_std: [10.0, 10.0, 10.0]
    vo_meas_std: [0.0001, 0.0001, 0.0001, 0.0001]
    rate: 400
    using_vo: 0

    
 